### ISSUE TITLE
This is cool. Can it be daemonized?

### ISSUE THREAD

**Issue by xplshn** [VHSgunzo/shellsrv#1]
Just a question/maybe a feature request? Can it be daemonized to expose a pseudofilesystem in /dev? That way you could pipe things to /dev/shsrv/*
Where '*' or the wildcard, would be the N clients that the daemon has connected to.
It'd be cool for working alongside SSH tunnels in a simpler way.

**Comment by VHSgunzo** [comment]
@xplshn 
Hello, clients PIDs tracking has been added in [v0.1.3](https://github.com/VHSgunzo/shellsrv/releases/tag/v0.1.3) [commit](https://github.com/VHSgunzo/shellsrv/commit/dff2ac00dfcff9f8af537a69bc7ca79534504af8).
By default, the directory where clients PIDs are linked is `"/tmp/ssrv$EUID/<socket>/<pid>"`
The location can be changed, see [usage](https://github.com/VHSgunzo/shellsrv?tab=readme-ov-file#usage).
And yes, the server can be demonized, for example, using the systemd unit (or another initialization system) or even simply sending it to the background with the `nohup shellsrv -server &>/dev/null &` (here the shellsrv log is sent to /dev/null)
